### ISSUE TITLE
Long-standing Crash Issues

### ISSUE THREAD

**Issue by Vysair** [Jays2Kings/tachiyomiJ2K#1595]
### Steps to reproduce

There are several ways that I believe could trigger the crash but often times it is very unexpected and random.

A - Details Page Categories Forced Exit
1. Tap on an entry to open up their details page
2. Proceed to read chapters normally
3. Exit the reader
4. Tap Edit categories/Add to categories
5. App is forcibly exited

Now, on scenario A, it does not matter if you even managed to edit the categories or not as it will crash your app once it tries to load the categories list I'm assuming. This is the most frequent crashes I've had. It does not discriminate whether I am on a Browse, Library or Global Search (not indexing the library). I'm guessing you are more likely to crash as well if you have read more than 4 chapters or long enough.

B - Reader Hang/Reader Freeze Then Crash
1. Read the chapters normally
_*Frequency is higher on Webtoon Mode compared to the Left to Right_

For this scenario B, it is more intriguing as sometimes the Not Responding dialog can goes many way. Firstly, if you choose to ignore the dialog and wait around 1m - 3m, it would stopped freezing but this is a rare occurrence. Secondly, if you tap the Wait button each time the dialog would appears, eventually it will goes away maybe after 5 - 10 dialog. Lastly, this is the most case I've got. If you choose to ignore the dialog, eventually it will forcibly exit the app OR will continues display the dialog no matter how many times you've had closed it as it keeps appearing two seconds after closing it using Wait prompt.

On this scenario B, at first I suspected it was memory issues but after monitoring them, I see no issues so I'm ruling that out for now. It was not laggy either.

C - Random Hang Then Crash
1. Do anything within the app

This is the final one. I cannot pinpoint the exact trigger as it happens anywhere within the app. Settings, Library, Chapter Scrollings and even on Idle.

PS. Please ignore the Not Responding dialog when I refresh as it often disappear on its own after it finishes refreshing OR if I restart the app and resume the refresh (assuming it's still on memory).

Specifically probably this (don't quote me on this)
`2829  9667 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6`
`2829  9667 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 2829`
`2829  9667 E AndroidRuntime: com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = RawQuery{query='`

### Expected behavior

There would be no such dialog.

### Actual behavior

Below are the three crashes dialog

1 - [TachiyomiJ2K isn't Responding](https://i.imgur.com/IROjLZ8.jpg)
_*This one appears the most frequent and is the default dialog_

2 - [Clear cache for TachiyomiJ2K?](https://i.imgur.com/aOqK1a4.jpg)
_*Would appear if the #1 have appeared within a short timeframe_

3 - [Something went wrong with TachiyomiJ2K](https://i.imgur.com/zmPJTP1.jpg)
_*This would appear after having repeatedly crashes_

_Not all time you get a dialog as the app exit faster than a system could catches it._

### Crash logs

[tachiyomi_crash_logs16.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/12258931/tachiyomi_crash_logs16.txt)
[tachiyomi_crash_logs17 pastebin](https://pastebin.com/Vh6rgK0P)
_*This is the crash log after the app reinstallation and also the first crash dialog I had since the reinstallation. I have only began using the app for a couple of hours I believe_

### TachiyomiJ2K version

1.6.6

### Android version

OneUI 5.1 (Android 13)

### Device

Galaxy Tab S6 Lite (2020)

### Other details

**Notes**
There are a few lines of error I would like to note as it coincides with my crash dialog however do note that I myself am not too sure about this as the dialog could appear way later than the actual error time as sometimes I can see some mismatches 

`32096   877 E FrameEvents: updateAcquireFence: Did not find frame.`
`32096 32096 E e.tachiyomi.j2k: Not starting debugger since process cannot load the jdwp agent.`

**Declaration**
I am aware of the several related threads regarding the issues, however the data provided is often insufficient and I wanted to compose it in far more specific details as I have been seeing this crash for as long as I have been using the app.

**Thread of similar issues**
[Thread by [BitSchism](https://github.com/Jays2Kings/tachiyomiJ2K/issues?q=is%3Aissue+is%3Aopen+author%3ABitSchism)](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1579)
[Thread by [MrChuw](https://github.com/Jays2Kings/tachiyomiJ2K/issues?q=is%3Aissue+is%3Aopen+author%3AMrChuw)](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1565)
[Thread by [kyzsuukii](https://github.com/kyzsuukii)](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1562)
[Thread by [JuanCRMorenoo](https://github.com/JuanCRMorenoo)](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1538)
[Thready by [Cloudninjakip](https://github.com/Jays2Kings/tachiyomiJ2K/issues?q=is%3Aissue+is%3Aopen+author%3ACloudninjakip)](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1519)

**Clarifications**

- There are about 4,000 - 5,000 entries in the library and 175 categories in total. 
- Transition is disabled so chapters webtoon especially would appear seamless.
- Show all categories is disabled as I extensively uses my categories like a tag/folder.
- 32-bit color is disabled as it eats up unnecessary resources.
- Always-on background service is only GlassWire and Mullvad VPN.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.6](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by BitSchism** [comment]
Mine was either largely resolved with an update or by deleting some downloaded chapters. I can't be sure which.

**Comment by Vysair** [comment]
> @Vysair Mine was either largely resolved with an update or by deleting some downloaded chapters. I can't be sure which.

I read live so I can rule out downloaded chapters (20GB/month would kill my sd card). I had both software update (from OneUI 4.0 to OneUI 5.1) and years worth of tachi update but the issues still persist sadly. Even after a reinstall of the app.
