### ISSUE TITLE
[Bug] "Refresh tracking metadata" does not fix manga with broken "Unknown Status" tracked using AniList

### ISSUE THREAD

**Issue by AlphaCentauri** [Jays2Kings/tachiyomiJ2K#303]
### Device information
* Tachiyomi version: 1.0.1
* Android phone & version: Pixel 3 XL / Android 10 (QQ2A.200405.005)

## Steps to reproduce
1. Identify and confirm you have a manga, tracked by AniList, with status shown as "Unknown Status" (ideally one you previously knew was being tracked properly)
1.1 As to how you get an entry into this state it seems to happen when restoring from backups (at least it did for me way back when I switched to J2K from stable)
2. Tap on Settings -> Advanced -> Refresh tracking metadata

### Expected behavior
Tracking should be refreshed and "Unknown Status" should now be updated to whatever is marked on AniList for that entry.

### Actual behavior
Nothing is updated, "Unknown Status" remains.

**Comment by Jays2Kings** [comment]
Is this now fixed with 1.0.2?

**Comment by AlphaCentauri** [comment]
It doesn't seem to be, no. I still have a few entries listed as "Unknown Status" and attempting to mass refresh still doesn't seem to work. I tried a couple times just to be sure.
