### ISSUE TITLE
[Bug] When sorting by last updated, a group of manga appear at the top which are all out of order

### ISSUE THREAD

**Issue by apav** [Jays2Kings/tachiyomiJ2K#35]
I have my library sorted by last updated, with the most recent appearing first. However, there is this group of manga at the top that aren't sorted by date. Here are each one's source and latest chapter date, in the order it was sorted:

LHTranslation 12/23/19
LHTranslation 12/6/19
Mangasushi 1/3/20
Mangasushi 1/5/20
LHTranslation  12/31/19
LHTranslation 1/1/20
Mangasushi 1/5/20
LHTranslation 12/16/19
LHTranslation 12/23/19
LHTranslation 12/30/19
LHTranslation 12/23/19
LHTranslation 11/6/19
LHTranslation 1/2/20
Mangapark 1/6/19

After that the rest of my manga are properly sorted, starting at 1/6/20 (today) every manga's last chapter is older than the last. 

I think I have an idea as to why this is happening. I noticed yesterday when I was migrating that a lot of the dates for LHTranslation manga chapters on Tachiyomi 
are incorrect by a few days, they don't match the date on their website. But the Mangasushi and Mangapark ones appear to be correct going by their website dates. And even though they're grouped at the top for whatever reason, that still doesn't explain why within this group their dates aren't being properly sorted.

Do you have any idea what the issue is here and if it's something that can be fixed with Tachiyomi? Thanks!

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi/issues/2217

**Comment by CarlosEsco** [comment]
read my comment there

**Comment by apav** [comment]
> read my comment there

Jay said to me "at least on my fork the last updated does sort by newest chapter" and it's 90% working correctly, except for this group of chapters sitting above the rest of my library that's properly sorted.

**Comment by Jays2Kings** [comment]
So this should be fixed now completely as of .69

you may have to pull to refresh on your library to get the correct dates

**Comment by apav** [comment]
Restored and refreshed library, it's still not working correctly for me sadly. I still have a group of manga at the top whose last chapters dates are all out of order. Underneath it is the rest of my library which is correctly sorted by last chapter date. 


Thanks so much for your effort.

**Comment by Jays2Kings** [comment]
Can you give me a backup file or list of manga/sources so I can test this. The sorting sorts by last newest chapter, not by the highest chapter and its date.

**Comment by Jays2Kings** [comment]
Actually don't worry about it, I see the issue now

**Comment by Jays2Kings** [comment]
This should be fully fixed now as of 0.9.7, refresh your manga so it's the correct date

**Comment by apav** [comment]
Thanks, it seems to be working except for one manga though. 

![Screenshot_20200116-025605](https://user-images.githubusercontent.com/8137930/72514472-e110ed00-380b-11ea-965f-ed8b8fa7838b.jpg)

This manga is sorted as the oldest title in last updated, despite it having a relatively recent last chapter and other titles being years older.

**Comment by Jays2Kings** [comment]
Can you show me a manga that is ranked higher with an older date?

**Comment by apav** [comment]
> Can you show me a manga that is ranked higher with an older date?

Strange, after another restore and library refresh it seems to have put that manga where it belongs in the order of last chapter date. Not sure why it sorted it next to my other oldest titles at first. I'm going to reset everything, reinstall the app, restore from backup and refresh to double check that it still works as intended.

**Comment by apav** [comment]
After a full app reset, restore, and library refresh it is still sorting correctly. Thanks so much for fixing this! I'll let you know if I spot any abnormalities with it in the future.
