### ISSUE TITLE
No network connection available when using VPN

### ISSUE THREAD

**Issue by cahvireyu** [Jays2Kings/tachiyomiJ2K#387]
**App version:** 1.0.4

**Android version:** 7.1.2

**Issue/Request:** Can't update anything with a VPN

**Steps to reproduce (if applicable)**

 1. Update/Add any titles or go to Settings>About and tap Version while using a VPN.

**Other details:**

Downgrading to v1.0.2 works just fine

**Comment by Jerrk** [comment]
i have the same issue, using wireguard on android 9

**Comment by Jays2Kings** [comment]
Fixed

**Comment by cahvireyu** [comment]
Thank you!

**Comment by Jerrk** [comment]
It appears this issue is back in the latest release.

Being connected to the VPN while trying to download something with "only download over wi-fi" enabled. shows the error "no wi-fi connection availible". Turning off the VPN makes the chapters start downloading instantly.
